# Setup
title:               민야호
tagline:             '희희'
description:         '이것저것 기록공간'
  # 'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://jhmin128.github.io
baseurl:             ""
paginate:            5
permalink:           pretty
collections:
  category:
    output: true

# About/contact
author:
  name:              Juhee Min # Mark Otto
  url:               https://open.kakao.com/o/sF7J9M8e # https://twitter.com/mdo
  email:             jhmin128@gmail.com # markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: G-74W5YXN7V8
remote-theme: poole/lanyon
